### PR TITLE
Fixes sending numbers larger than 4294967296 (int32)

### PR DESCRIPTION
**Pull request by natcl**

### CODE REVIEW

**Comment by njh** [comment]
Is this actually a bug with the OSC node module?
Seems like it should get this right - it doesn't have anything to do with Node-RED.

I thought the same thing about detecting sending NULL.

**Comment by natcl** [comment]
No that's not a bug in the OSC node module, see this conversation I had with author:
https://github.com/colinbdclark/osc.js/issues/62

The other library behaves the same by the way.

**Comment by njh** [comment]
Sorry, I still don't understand why this is Node-RED specific.

Why doesn't the osc library automatically encode to Long if the number if greater than 4294967296?

**Comment by natcl** [comment]
As the author of the osc library stated he'd rather have the user decide what type of data to send, I don't really see a problem with this, the former library also had this issue.
Did you have something else to propose ?

**Pull request closed without merging**
