### PR TITLE
Major refactor to make it transport independant

### PR DESCRIPTION
**Pull request by natcl**
Hi !
Here's my re-factor to make it transport independant.  Let me know what you think !

### CODE REVIEW

**Comment by njh** [comment]
Something is weird with this PR - I think you started with an old version, so this PR doesn't apply cleanly?

**Comment by natcl** [comment]
I think it's because I changed a lot of things so it can't be
auto-merged... I'm not sure about the workflow on Github in that case but I
will check.

Le lun. 9 mai 2016 à 04:03, Nicholas Humfrey notifications@github.com a
écrit :

**Comment by natcl** [comment]
I just checked and we'll have to merge manually as they are too many changes.  Here's what I think will work:

```
git remote add natcl https://github.com/natcl/node-red-contrib-osc.git
git fetch natcl
git merge natcl/master
```

It'll then complain about conflicts.  The easy way would be to replace all the files by the ones from my repo or you can go through each file and resolve the conflicts.  You would then commit normally.

Let me know if you need more help with this !

**Comment by njh** [comment]
I think I will import the change as a single commit.

Lots of the commit messages are quite meaningless anyway ("More progress"). I much prefer Atomic commits.

What is the purpose of the "project" directory?

**Comment by natcl** [comment]
Makes sense.
The project folder is a way to quickly test your node in an local node-red
instance. You cd to the project directory and npm install/npm start and
you're up and running. I also manage the examples there. I excluded it from
npm.

Le lun. 9 mai 2016 à 10:13, Nicholas Humfrey notifications@github.com a
écrit :

**Comment by natcl** [comment]
Also let me know if you have suggestions/improvements I don't want to
impose anything !

**Comment by natcl** [comment]
Just a small video Teaser :)
https://youtu.be/dQleQlkBE58

**Comment by natcl** [comment]
Hello !
Just curious to see if you're still up to merging this with the main repo, let me know !
Thanks !

**Comment by njh** [comment]
Now merged into this branch:
https://github.com/njh/node-red-contrib-osc/tree/natcl

Going to do some more testing on it before merging to master and releasing version 1.0.0

**Comment by njh** [comment]
Sadly I can't get your new node to work with my main testcase.

I have an MP3 playing audio deck:
https://www.aelius.com/njh/madjack/

Which accepts commands like `/deck/play` but does not use any parameters.
With the payload as an empty string it sends the type field as 's'.

If `msg.payload` is NULL, it causes exceptions in the node.

**Comment by natcl** [comment]
Ok I'll check this, I'm not sure sending empty values is part of the OSC spec...

**Comment by natcl** [comment]
Did you try just sending nothing as the payload ? Here my test client doesn't seem to complain (Max/MSP)

[{"id":"7b2ff9ba.84d008","type":"inject","z":"67ebe42d.98141c","name":"","topic":"/deck/play","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"x":328.5,"y":119,"wires":[["bed06b8.f412f98"]]},{"id":"bed06b8.f412f98","type":"osc","z":"67ebe42d.98141c","name":"","path":"","slip":false,"metadata":false,"x":547.5,"y":120,"wires":[["24d79e2e.db2862"]]},{"id":"24d79e2e.db2862","type":"udp out","z":"67ebe42d.98141c","name":"","addr":"localhost","iface":"","port":"3333","ipv":"udp4","outport":"","base64":false,"multicast":"false","x":785.5,"y":118,"wires":[]}]

**Comment by natcl** [comment]
Ah I understand, working on a fix...

**Comment by natcl** [comment]
I just pushed a fix, I'm sending type 'N' when a payload is empty.
Let me know if it works for you.

**Comment by natcl** [comment]
Also worth mentioning, even without the fix you can send a nil value like this, by setting an inject node to json with this:  {"type": "N", "value": null}

```
[{"id":"e2d638be.1d29c8","type":"inject","z":"5e5d4cea.a1a2b4","name":"","topic":"/deck/play","payload":"{\"type\": \"N\", \"value\": null}","payloadType":"json","repeat":"","crontab":"","once":false,"x":161.5,"y":556,"wires":[["bf7a29be.4085d8"]]}]
```

**Comment by natcl** [comment]
Hello ! did you get the chance to check the correction ?

Thanks !

**Comment by njh** [comment]
Fixed my problem in 5d399060e9e4b76422a5f73899e82a2ce5362c8c

**Comment by njh** [comment]
Done a few tweaks and merged into master.

Can you test to see if it works for you still?

There are some complex paths though this code.
I am missing unit tests :(

**Comment by njh** [comment]
Closing this pull request because it is merged now and commenting on #5

**Pull request closed without merging**
